### File Variables

@hostname = localhost
@port = 7071
@host = {{hostname}}:{{port}}

### Welcome 
GET http://{{host}}/api/Welcome

### Welcome 
GET https://func-enterpriseserverless-01-eastus2.azurewebsites.net/api/Welcome